### ISSUE TITLE
Setting nested array values does not work properly

### ISSUE THREAD

**Issue by clayne11** [aldeed/node-mongo-object#1]
The code in `setValueForPosition` only looks for array paths (`foo[0]`) but not for object paths (ex `foo.bar`).

This causes issues when trying to set paths like `one.two[3].four`.

I will be submitting a PR with a fix along with a test showing the issue.

**Comment by aldeed** [comment]
I believe this has since been fixed but if anyone wants to submit a new issue with some code that reproduces the issue, please do.
